<?php

return [
    'pokemons' => [
        [
            'name' => 'Bulbasaur',
            'type' => 'Erba/Veleno',
            'hp' => 45,
            'sprite' => '1.png',
        ],
        [
            'name' => 'Ivysaur',
            'type' => 'Erba/Veleno',
            'hp' => 60,
            'sprite' => '2.png',
        ],
        [
            'name' => 'Venusaur',
            'type' => 'Erba/Veleno',
            'hp' => 80,
            'sprite' => '3.png',
        ],
        [
            'name' => 'Charmander',
            'type' => 'Fuoco',
            'hp' => 39,
            'sprite' => '4.png',
        ],
        [
            'name' => 'Charmeleon',
            'type' => 'Fuoco',
            'hp' => 58,
            'sprite' => '5.png',
        ],
        [
            'name' => 'Charizard',
            'type' => 'Fuoco/Volante',
            'hp' => 78,
            'sprite' => '6.png',
        ],
        [
            'name' => 'Squirtle',
            'type' => 'Acqua',
            'hp' => 44,
            'sprite' => '7.png',
        ],
        [
            'name' => 'Wartortle',
            'type' => 'Acqua',
            'hp' => 59,
            'sprite' => '8.png',
        ],
        [
            'name' => 'Blastoise',
            'type' => 'Acqua',
            'hp' => 79,
            'sprite' => '9.png',
        ],
        [
            'name' => 'Caterpie',
            'type' => 'Coleottero',
            'hp' => 45,
            'sprite' => '10.png',
        ],
        [
            'name' => 'Metapod',
            'type' => 'Coleottero',
            'hp' => 50,
            'sprite' => '11.png',
        ],
        [
            'name' => 'Butterfree',
            'type' => 'Coleottero/Volante',
            'hp' => 60,
            'sprite' => '12.png',
        ],
        [
            'name' => 'Weedle',
            'type' => 'Coleottero/Veleno',
            'hp' => 40,
            'sprite' => '13.png',
        ],
        [
            'name' => 'Kakuna',
            'type' => 'Coleottero/Veleno',
            'hp' => 45,
            'sprite' => '14.png',
        ],
        [
            'name' => 'Beedrill',
            'type' => 'Coleottero/Veleno',
            'hp' => 65,
            'sprite' => '15.png',
        ],
        [
            'name' => 'Pidgey',
            'type' => 'Normale/Volante',
            'hp' => 40,
            'sprite' => '16.png',
        ],
        [
            'name' => 'Pidgeotto',
            'type' => 'Normale/Volante',
            'hp' => 63,
            'sprite' => '17.png',
        ],
        [
            'name' => 'Pidgeot',
            'type' => 'Normale/Volante',
            'hp' => 83,
            'sprite' => '18.png',
        ],
        [
            'name' => 'Rattata',
            'type' => 'Normale',
            'hp' => 30,
            'sprite' => '19.png',
        ],
        [
            'name' => 'Raticate',
            'type' => 'Normale',
            'hp' => 55,
            'sprite' => '20.png',
        ],
        [
            'name' => 'Spearow',
            'type' => 'Normale/Volante',
            'hp' => 40,
            'sprite' => '21.png',
        ],
        [
            'name' => 'Fearow',
            'type' => 'Normale/Volante',
            'hp' => 65,
            'sprite' => '22.png',
        ],
        [
            'name' => 'Ekans',
            'type' => 'Veleno',
            'hp' => 35,
            'sprite' => '23.png',
        ],
        [
            'name' => 'Arbok',
            'type' => 'Veleno',
            'hp' => 60,
            'sprite' => '24.png',
        ],
        [
            'name' => 'Pikachu',
            'type' => 'Elettro',
            'hp' => 35,
            'sprite' => '25.png',
        ],
        [
            'name' => 'Raichu',
            'type' => 'Elettro',
            'hp' => 60,
            'sprite' => '26.png',
        ],
        [
            'name' => 'Sandshrew',
            'type' => 'Terra',
            'hp' => 50,
            'sprite' => '27.png',
        ],
        [
            'name' => 'Sandslash',
            'type' => 'Terra',
            'hp' => 75,
            'sprite' => '28.png',
        ],
        [
            'name' => 'Nidoran♀',
            'type' => 'Veleno',
            'hp' => 55,
            'sprite' => '29.png',
        ],
        [
            'name' => 'Nidorina',
            'type' => 'Veleno',
            'hp' => 70,
            'sprite' => '30.png',
        ],
        [
            'name' => 'Nidoqueen',
            'type' => 'Veleno/Terra',
            'hp' => 90,
            'sprite' => '31.png',
        ],
        [
            'name' => 'Nidoran♂',
            'type' => 'Veleno',
            'hp' => 46,
            'sprite' => '32.png',
        ],
        [
            'name' => 'Nidorino',
            'type' => 'Veleno',
            'hp' => 61,
            'sprite' => '33.png',
        ],
        [
            'name' => 'Nidoking',
            'type' => 'Veleno/Terra',
            'hp' => 81,
            'sprite' => '34.png',
        ],
        [
            'name' => 'Clefairy',
            'type' => 'Folletto',
            'hp' => 70,
            'sprite' => '35.png',
        ],
        [
            'name' => 'Clefable',
            'type' => 'Folletto',
            'hp' => 95,
            'sprite' => '36.png',
        ],
        [
            'name' => 'Vulpix',
            'type' => 'Fuoco',
            'hp' => 38,
            'sprite' => '37.png',
        ],
        [
            'name' => 'Ninetales',
            'type' => 'Fuoco',
            'hp' => 73,
            'sprite' => '38.png',
        ],
        [
            'name' => 'Jigglypuff',
            'type' => 'Normale/Folletto',
            'hp' => 115,
            'sprite' => '39.png',
        ],
        [
            'name' => 'Wigglytuff',
            'type' => 'Normale/Folletto',
            'hp' => 140,
            'sprite' => '40.png',
        ],
        [
            'name' => 'Zubat',
            'type' => 'Veleno/Volante',
            'hp' => 40,
            'sprite' => '41.png',
        ],
        [
            'name' => 'Golbat',
            'type' => 'Veleno/Volante',
            'hp' => 75,
            'sprite' => '42.png',
        ],
        [
            'name' => 'Oddish',
            'type' => 'Erba/Veleno',
            'hp' => 45,
            'sprite' => '43.png',
        ],
        [
            'name' => 'Gloom',
            'type' => 'Erba/Veleno',
            'hp' => 60,
            'sprite' => '44.png',
        ],
        [
            'name' => 'Vileplume',
            'type' => 'Erba/Veleno',
            'hp' => 75,
            'sprite' => '45.png',
        ],
        [
            'name' => 'Paras',
            'type' => 'Coleottero/Erba',
            'hp' => 35,
            'sprite' => '46.png',
        ],
        [
            'name' => 'Parasect',
            'type' => 'Coleottero/Erba',
            'hp' => 60,
            'sprite' => '47.png',
        ],
        [
            'name' => 'Venonat',
            'type' => 'Coleottero/Veleno',
            'hp' => 60,
            'sprite' => '48.png',
        ],
        [
            'name' => 'Venomoth',
            'type' => 'Coleottero/Veleno',
            'hp' => 70,
            'sprite' => '49.png',
        ],
        [
            'name' => 'Diglett',
            'type' => 'Terra',
            'hp' => 10,
            'sprite' => '50.png',
        ],
        [
            'name' => 'Dugtrio',
            'type' => 'Terra',
            'hp' => 35,
            'sprite' => '51.png',
        ],
        [
            'name' => 'Meowth',
            'type' => 'Normale',
            'hp' => 40,
            'sprite' => '52.png',
        ],
        [
            'name' => 'Persian',
            'type' => 'Normale',
            'hp' => 65,
            'sprite' => '53.png',
        ],
        [
            'name' => 'Psyduck',
            'type' => 'Acqua',
            'hp' => 50,
            'sprite' => '54.png',
        ],
        [
            'name' => 'Golduck',
            'type' => 'Acqua',
            'hp' => 80,
            'sprite' => '55.png',
        ],
        [
            'name' => 'Mankey',
            'type' => 'Lotta',
            'hp' => 40,
            'sprite' => '56.png',
        ],
        [
            'name' => 'Primeape',
            'type' => 'Lotta',
            'hp' => 65,
            'sprite' => '57.png',
        ],
        [
            'name' => 'Growlithe',
            'type' => 'Fuoco',
            'hp' => 55,
            'sprite' => '58.png',
        ],
        [
            'name' => 'Arcanine',
            'type' => 'Fuoco',
            'hp' => 90,
            'sprite' => '59.png',
        ],
        [
            'name' => 'Poliwag',
            'type' => 'Acqua',
            'hp' => 40,
            'sprite' => '60.png',
        ],
        [
            'name' => 'Poliwhirl',
            'type' => 'Acqua',
            'hp' => 65,
            'sprite' => '61.png',
        ],
        [
            'name' => 'Poliwrath',
            'type' => 'Acqua/Lotta',
            'hp' => 90,
            'sprite' => '62.png',
        ],
        [
            'name' => 'Abra',
            'type' => 'Psichico',
            'hp' => 25,
            'sprite' => '63.png',
        ],
        [
            'name' => 'Kadabra',
            'type' => 'Psichico',
            'hp' => 40,
            'sprite' => '64.png',
        ],
        [
            'name' => 'Alakazam',
            'type' => 'Psichico',
            'hp' => 55,
            'sprite' => '65.png',
        ],
        [
            'name' => 'Machop',
            'type' => 'Lotta',
            'hp' => 70,
            'sprite' => '66.png',
        ],
        [
            'name' => 'Machoke',
            'type' => 'Lotta',
            'hp' => 80,
            'sprite' => '67.png',
        ],
        [
            'name' => 'Machamp',
            'type' => 'Lotta',
            'hp' => 90,
            'sprite' => '68.png',
        ],
        [
            'name' => 'Bellsprout',
            'type' => 'Erba/Veleno',
            'hp' => 50,
            'sprite' => '69.png',
        ],
        [
            'name' => 'Weepinbell',
            'type' => 'Erba/Veleno',
            'hp' => 65,
            'sprite' => '70.png',
        ],
        [
            'name' => 'Victreebel',
            'type' => 'Erba/Veleno',
            'hp' => 80,
            'sprite' => '71.png',
        ],
        [
            'name' => 'Tentacool',
            'type' => 'Acqua/Veleno',
            'hp' => 40,
            'sprite' => '72.png',
        ],
        [
            'name' => 'Tentacruel',
            'type' => 'Acqua/Veleno',
            'hp' => 80,
            'sprite' => '73.png',
        ],
        [
            'name' => 'Geodude',
            'type' => 'Roccia/Terra',
            'hp' => 40,
            'sprite' => '74.png',
        ],
        [
            'name' => 'Graveler',
            'type' => 'Roccia/Terra',
            'hp' => 55,
            'sprite' => '75.png',
        ],
        [
            'name' => 'Golem',
            'type' => 'Roccia/Terra',
            'hp' => 80,
            'sprite' => '76.png',
        ],
        [
            'name' => 'Ponyta',
            'type' => 'Fuoco',
            'hp' => 50,
            'sprite' => '77.png',
        ],
        [
            'name' => 'Rapidash',
            'type' => 'Fuoco',
            'hp' => 65,
            'sprite' => '78.png',
        ],
        [
            'name' => 'Slowpoke',
            'type' => 'Acqua/Psico',
            'hp' => 90,
            'sprite' => '79.png',
        ],
        [
            'name' => 'Slowbro',
            'type' => 'Acqua/Psico',
            'hp' => 95,
            'sprite' => '80.png',
        ],
        [
            'name' => 'Magnemite',
            'type' => 'Elettro/Acciaio',
            'hp' => 25,
            'sprite' => '81.png',
        ],
        [
            'name' => 'Magneton',
            'type' => 'Elettro/Acciaio',
            'hp' => 50,
            'sprite' => '82.png',
        ],
        [
            'name' => 'Farfetch\'d',
            'type' => 'Normale/Volante',
            'hp' => 52,
            'sprite' => '83.png',
        ],
        [
            'name' => 'Doduo',
            'type' => 'Normale/Volante',
            'hp' => 35,
            'sprite' => '84.png',
        ],
        [
            'name' => 'Dodrio',
            'type' => 'Normale/Volante',
            'hp' => 60,
            'sprite' => '85.png',
        ],
        [
            'name' => 'Seel',
            'type' => 'Acqua',
            'hp' => 65,
            'sprite' => '86.png',
        ],
        [
            'name' => 'Dewgong',
            'type' => 'Acqua/Ghiaccio',
            'hp' => 90,
            'sprite' => '87.png',
        ],
        [
            'name' => 'Grimer',
            'type' => 'Veleno',
            'hp' => 80,
            'sprite' => '88.png',
        ],
        [
            'name' => 'Muk',
            'type' => 'Veleno',
            'hp' => 105,
            'sprite' => '89.png',
        ],
        [
            'name' => 'Shellder',
            'type' => 'Acqua',
            'hp' => 30,
            'sprite' => '90.png',
        ],
        [
            'name' => 'Cloyster',
            'type' => 'Acqua/Ghiaccio',
            'hp' => 50,
            'sprite' => '91.png',
        ],
        [
            'name' => 'Gastly',
            'type' => 'Spettro/Veleno',
            'hp' => 30,
            'sprite' => '92.png',
        ],
        [
            'name' => 'Haunter',
            'type' => 'Spettro/Veleno',
            'hp' => 45,
            'sprite' => '93.png',
        ],
        [
            'name' => 'Gengar',
            'type' => 'Spettro/Veleno',
            'hp' => 60,
            'sprite' => '94.png',
        ],
        [
            'name' => 'Onix',
            'type' => 'Roccia/Terra',
            'hp' => 35,
            'sprite' => '95.png',
        ],
        [
            'name' => 'Drowzee',
            'type' => 'Psico',
            'hp' => 60,
            'sprite' => '96.png',
        ],
        [
            'name' => 'Hypno',
            'type' => 'Psico',
            'hp' => 85,
            'sprite' => '97.png',
        ],
        [
            'name' => 'Krabby',
            'type' => 'Acqua',
            'hp' => 30,
            'sprite' => '98.png',
        ],
        [
            'name' => 'Kingler',
            'type' => 'Acqua',
            'hp' => 55,
            'sprite' => '99.png',
        ],
        [
            'name' => 'Voltorb',
            'type' => 'Elettro',
            'hp' => 40,
            'sprite' => '100.png',
        ],
        [
            'name' => 'Electrode',
            'type' => 'Elettro',
            'hp' => 60,
            'sprite' => '101.png',
        ],
        [
            'name' => 'Exeggcute',
            'type' => 'Erba/Psico',
            'hp' => 60,
            'sprite' => '102.png',
        ],
        [
            'name' => 'Exeggutor',
            'type' => 'Erba/Psico',
            'hp' => 95,
            'sprite' => '103.png',
        ],
        [
            'name' => 'Cubone',
            'type' => 'Terra',
            'hp' => 50,
            'sprite' => '104.png',
        ],
        [
            'name' => 'Marowak',
            'type' => 'Terra',
            'hp' => 60,
            'sprite' => '105.png',
        ],
        [
            'name' => 'Hitmonlee',
            'type' => 'Lotta',
            'hp' => 50,
            'sprite' => '106.png',
        ],
        [
            'name' => 'Hitmonchan',
            'type' => 'Lotta',
            'hp' => 50,
            'sprite' => '107.png',
        ],
        [
            'name' => 'Lickitung',
            'type' => 'Normale',
            'hp' => 90,
            'sprite' => '108.png',
        ],
        [
            'name' => 'Koffing',
            'type' => 'Veleno',
            'hp' => 40,
            'sprite' => '109.png',
        ],
        [
            'name' => 'Weezing',
            'type' => 'Veleno',
            'hp' => 65,
            'sprite' => '110.png',
        ],
        [
            'name' => 'Rhyhorn',
            'type' => 'Terra/Roccia',
            'hp' => 80,
            'sprite' => '111.png',
        ],
        [
            'name' => 'Rhydon',
            'type' => 'Terra/Roccia',
            'hp' => 105,
            'sprite' => '112.png',
        ],
        [
            'name' => 'Chansey',
            'type' => 'Normale',
            'hp' => 250,
            'sprite' => '113.png',
        ],
        [
            'name' => 'Tangela',
            'type' => 'Erba',
            'hp' => 65,
            'sprite' => '114.png',
        ],
        [
            'name' => 'Kangaskhan',
            'type' => 'Normale',
            'hp' => 105,
            'sprite' => '115.png',
        ],
        [
            'name' => 'Horsea',
            'type' => 'Acqua',
            'hp' => 30,
            'sprite' => '116.png',
        ],
        [
            'name' => 'Seadra',
            'type' => 'Acqua',
            'hp' => 55,
            'sprite' => '117.png',
        ],
        [
            'name' => 'Goldeen',
            'type' => 'Acqua',
            'hp' => 45,
            'sprite' => '118.png',
        ],
        [
            'name' => 'Seaking',
            'type' => 'Acqua',
            'hp' => 80,
            'sprite' => '119.png',
        ],
        [
            'name' => 'Staryu',
            'type' => 'Acqua',
            'hp' => 30,
            'sprite' => '120.png',
        ],
        [
            'name' => 'Starmie',
            'type' => 'Acqua/Psico',
            'hp' => 60,
            'sprite' => '121.png',
        ],
        [
            'name' => 'Mr. Mime',
            'type' => 'Psico/Folletto',
            'hp' => 40,
            'sprite' => '122.png',
        ],
        [
            'name' => 'Scyther',
            'type' => 'Coleottero/Volante',
            'hp' => 70,
            'sprite' => '123.png',
        ],
        [
            'name' => 'Jynx',
            'type' => 'Ghiaccio/Psico',
            'hp' => 65,
            'sprite' => '124.png',
        ],
        [
            'name' => 'Electabuzz',
            'type' => 'Elettro',
            'hp' => 65,
            'sprite' => '125.png',
        ],
        [
            'name' => 'Magmar',
            'type' => 'Fuoco',
            'hp' => 65,
            'sprite' => '126.png',
        ],
        [
            'name' => 'Pinsir',
            'type' => 'Coleottero',
            'hp' => 65,
            'sprite' => '127.png',
        ],
        [
            'name' => 'Tauros',
            'type' => 'Normale',
            'hp' => 75,
            'sprite' => '128.png',
        ],
        [
            'name' => 'Magikarp',
            'type' => 'Acqua',
            'hp' => 20,
            'sprite' => '129.png',
        ],
        [
            'name' => 'Gyarados',
            'type' => 'Acqua/Volante',
            'hp' => 95,
            'sprite' => '130.png',
        ],
        [
            'name' => 'Lapras',
            'type' => 'Acqua/Ghiaccio',
            'hp' => 130,
            'sprite' => '131.png',
        ],
        [
            'name' => 'Ditto',
            'type' => 'Normale',
            'hp' => 48,
            'sprite' => '132.png',
        ],
        [
            'name' => 'Eevee',
            'type' => 'Normale',
            'hp' => 55,
            'sprite' => '133.png',
        ],
        [
            'name' => 'Vaporeon',
            'type' => 'Acqua',
            'hp' => 130,
            'sprite' => '134.png',
        ],
        [
            'name' => 'Jolteon',
            'type' => 'Elettro',
            'hp' => 65,
            'sprite' => '135.png',
        ],
        [
            'name' => 'Flareon',
            'type' => 'Fuoco',
            'hp' => 65,
            'sprite' => '136.png',
        ],
        [
            'name' => 'Porygon',
            'type' => 'Normale',
            'hp' => 65,
            'sprite' => '137.png',
        ],
        [
            'name' => 'Omanyte',
            'type' => 'Roccia/Acqua',
            'hp' => 35,
            'sprite' => '138.png',
        ],
        [
            'name' => 'Omastar',
            'type' => 'Roccia/Acqua',
            'hp' => 70,
            'sprite' => '139.png',
        ],
        [
            'name' => 'Kabuto',
            'type' => 'Roccia/Acqua',
            'hp' => 30,
            'sprite' => '140.png',
        ],
        [
            'name' => 'Kabutops',
            'type' => 'Roccia/Acqua',
            'hp' => 60,
            'sprite' => '141.png',
        ],
        [
            'name' => 'Aerodactyl',
            'type' => 'Roccia/Volante',
            'hp' => 80,
            'sprite' => '142.png',
        ],
        [
            'name' => 'Snorlax',
            'type' => 'Normale',
            'hp' => 160,
            'sprite' => '143.png',
        ],
        [
            'name' => 'Articuno',
            'type' => 'Ghiaccio/Volante',
            'hp' => 90,
            'sprite' => '144.png',
        ],
        [
            'name' => 'Zapdos',
            'type' => 'Elettro/Volante',
            'hp' => 90,
            'sprite' => '145.png',
        ],
        [
            'name' => 'Moltres',
            'type' => 'Fuoco/Volante',
            'hp' => 90,
            'sprite' => '146.png',
        ],
        [
            'name' => 'Dratini',
            'type' => 'Drago',
            'hp' => 41,
            'sprite' => '147.png',
        ],
        [
            'name' => 'Dragonair',
            'type' => 'Drago',
            'hp' => 61,
            'sprite' => '148.png',
        ],
        [
            'name' => 'Dragonite',
            'type' => 'Drago/Volante',
            'hp' => 91,
            'sprite' => '149.png',
        ],
        [
            'name' => 'Mewtwo',
            'type' => 'Psico',
            'hp' => 106,
            'sprite' => '150.png',
        ],
        [
            'name' => 'Mew',
            'type' => 'Psico',
            'hp' => 100,
            'sprite' => '151.png',
        ],
    ],
];